#!/bin/bash
clear

if [[ $1 = "all" ]]
then
    echo "Risque present : "
    grep "^### " /home/$USER/cheatsheet/* | awk -F '/' '{print $5}'

    echo
    echo "Couche par outils : "
    grep "^## " /home/$USER/cheatsheet/* | awk -F '/' '{print $5}'

elif [[ $1 = 'me' ]]
then
	cat /home/$USER/cheatsheet/$2.md
	echo
elif [[ -z $1 ]]
then
    read -p "Type d'approche :

    1 - Par Risque
    2 - Par couche OSI
    3 -	Par critere de securite
    
    selection : " ChoixApproche

    if [[ $ChoixApproche == 1 ]]
    then
        clear
        read -p "Type de risque :

        Usurpation
        Atteinte à la réputation/image
        Falsification
        Destruction
        Escalade de privilège
        Dégradation de privilèges
        Contournement
        Reproduction
        Dégradation / limitation
        Déni de services
        Divulgation des informations chiffrées
        Inaccessibilité des informations chiffrées

        Selection : " TypeRisque
        echo
        echo "$(grep -i "$TypeRisque" /home/$USER/cheatsheet/*)"

    elif [[ $ChoixApproche == 2 ]]
    then
        clear
        read -p "Couche OSI :

        7 - Applicative
        6 - Présentation
        5 - Session
        4 - Transport
        3 - Réseaux
        2 - Liaison
        1 - Physique

        Selection d'un numéro : " couche
        echo
        echo "$(grep -i "COUCHE $couche" /home/$USER/cheatsheet/*)"

	elif [[ $ChoixApproche == 3 ]]
    then
        clear
        read -p "Criteres de securite:

		Confidentialite
		Integrite
		Disponibilite

        Selection : " critere
        echo
        echo "$(grep -i "$critere" /home/$USER/cheatsheet/*)"
    else
        echo "ERREUR: Veuillez choisir entre l'option [1] et l'option [2]."
    fi
fi

